spring:
  application:
    name: Themeleaf
server:
  port: 8081
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  web:
   resources:
     static-locations: classpath:/static/